services:
  mem0_store:
    image: semitechnologies/weaviate:latest
    restart: unless-stopped
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
      - WEAVIATE_CLUSTER_URL=http://mem0_store:8080
    ports:
      - "8080:8080"
    volumes:
      - mem0_storage:/var/lib/weaviate