# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_events.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61gent_events.proto\x12\x06\x61gents\"\x18\n\x05Input\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0eInputProcessed\x12\r\n\x05route\x18\x01 \x01(\t\"\x19\n\x06Output\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rOutputWritten\x12\r\n\x05route\x18\x01 \x01(\t\"\x1a\n\x07IOError\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12NewMessageReceived\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x11ResponseGenerated\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1a\n\x07GoodBye\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rMessageStored\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x12\x43onversationClosed\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\"\x1b\n\x08Shutdown\x12\x0f\n\x07message\x18\x01 \x01(\tB!\xaa\x02\x1eMicrosoft.AutoGen.Abstractionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Microsoft.AutoGen.Abstractions'
  _globals['_INPUT']._serialized_start=30
  _globals['_INPUT']._serialized_end=54
  _globals['_INPUTPROCESSED']._serialized_start=56
  _globals['_INPUTPROCESSED']._serialized_end=87
  _globals['_OUTPUT']._serialized_start=89
  _globals['_OUTPUT']._serialized_end=114
  _globals['_OUTPUTWRITTEN']._serialized_start=116
  _globals['_OUTPUTWRITTEN']._serialized_end=146
  _globals['_IOERROR']._serialized_start=148
  _globals['_IOERROR']._serialized_end=174
  _globals['_NEWMESSAGERECEIVED']._serialized_start=176
  _globals['_NEWMESSAGERECEIVED']._serialized_end=213
  _globals['_RESPONSEGENERATED']._serialized_start=215
  _globals['_RESPONSEGENERATED']._serialized_end=252
  _globals['_GOODBYE']._serialized_start=254
  _globals['_GOODBYE']._serialized_end=280
  _globals['_MESSAGESTORED']._serialized_start=282
  _globals['_MESSAGESTORED']._serialized_end=314
  _globals['_CONVERSATIONCLOSED']._serialized_start=316
  _globals['_CONVERSATIONCLOSED']._serialized_end=375
  _globals['_SHUTDOWN']._serialized_start=377
  _globals['_SHUTDOWN']._serialized_end=404
# @@protoc_insertion_point(module_scope)
