name: run-openai-test-and-notebooks

on:
  pull_request_target:
    branches: [ "main" ]
    paths:
      - 'dotnet/**'
env:
  BUILD_CONFIGURATION: Release    # set this to the appropriate build configuration

jobs:
  build:
    environment: dotnet
    name: run-openai-test-and-notebooks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore
    - name: Restore tool
      run: dotnet tool restore
    - name: Build
      run: dotnet build --no-restore -p:VersionSuffix=$GITHUB_RUN_ID --configuration '${{ env.BUILD_CONFIGURATION }}'
    - name: Pack
      run: dotnet pack --no-restore -p:VersionSuffix=$GITHUB_RUN_ID --no-build --configuration '${{ env.BUILD_CONFIGURATION }}' --output ./artifacts
    - name: run all tests
      run: dotnet test --no-restore --no-build --configuration '${{ env.BUILD_CONFIGURATION }}'
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_GPT_35_MODEL_ID: ${{ secrets.AZURE_GPT_35_MODEL_ID }}

    - name: Add local feed
      run: dotnet nuget add source --name local artifacts --configfile NuGet.config
    - name: Perform a Pester test from the .tools/run_all_notebooks.ps1
      shell: pwsh
      run: |
        Invoke-Pester .tools/run_all_notebook.ps1 -Passthru
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_GPT_35_MODEL_ID: ${{ secrets.AZURE_GPT_35_MODEL_ID }}
      
