name: 🔒 Maintainer Only
description: Only use this template if you are a maintainer.

body:
  - type: checkboxes
    attributes:
      label: Confirmation
      description: Please only use this template if you are a maintainer. Thanks for helping us keep the issue tracker organized!
      options:
        - label: I confirm that I am a maintainer and so can use this template. If I am not, I understand this issue will be closed and I will be asked to use a different template.
          required: true

  - type: textarea
    id: body
    attributes:
      label: Issue body
      description: "How do you trigger this bug? Please walk us through it step by step."
    validations:
      required: true

