name: Feature Request
description: Request a new feature or enhancement
labels: ["feature"]

body:
  - type: textarea
    attributes:
      label: What feature would you like to be added?
      description: Please describe the desired feature. Be descriptive, provide examples and if possible, provide a proposed solution.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this needed?
      description: Why is it important that this feature is implemented? What problem or need does it solve?
    validations:
      required: true
