from typing import Any, List, Mapping, Protocol

from ..types import Message


class ChatMemory(Protocol):
    def add_message(self, message: Message) -> None: ...

    def get_messages(self) -> List[Message]: ...

    def clear(self) -> None: ...

    def save_state(self) -> Mapping[str, Any]: ...

    def load_state(self, state: Mapping[str, Any]) -> None: ...
