[build-system]
build-backend="hatchling.build"
requires     =[ "hatchling" ]

[project]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies=[ "autogen-core", "autogen-ext" ]
description="Generates a JSON schema for component config"
license={ file="LICENSE-CODE" }
name="component-schema-gen"
readme="README.md"
requires-python=">=3.10"
version="0.1.0"

[project.scripts]
gen-component-schema="component_schema_gen.__main__:main"

[tool.ruff]
extend ="../../pyproject.toml"
include=[ "src/**" ]

[tool.ruff.lint]
ignore=[ "T201" ]

[tool.pyright]
extends="../../pyproject.toml"
include=[ "src" ]

[tool.poe]
include="../../shared_tasks.toml"

[tool.poe.tasks]
mypy="mypy --config-file $POE_ROOT/../../pyproject.toml src"
test="python -c \"import sys; sys.exit(0)\""
