# Basic setup
FROM python:3.11-slim-bookworm

# Update and install necessary packages
RUN apt-get update && apt-get -y update
# added vim and nano for convenience
RUN apt-get install -y sudo git npm vim nano curl

# Setup a non-root user 'autogen' with sudo access
RUN adduser --disabled-password --gecos '' autogen
RUN adduser autogen sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER autogen
WORKDIR /home/autogen

# Set environment variable
# ENV OPENAI_API_KEY="{OpenAI-API-Key}"

# Clone the AutoGen repository
# RUN git clone https://github.com/microsoft/autogen.git /home/autogen/autogen
RUN git clone https://github.com/r3d91ll/autogen.git /home/autogen/autogen
WORKDIR /home/autogen/autogen

# Install AutoGen in editable mode with extra components
RUN sudo pip install -e .[test,teachable,lmm,retrievechat,mathchat,blendsearch]

# Install pre-commit hooks
RUN pre-commit install

# Install tools for documentation
# Using the Debian package for Yarn is a more reliable way to install it
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN sudo apt-get update && sudo apt-get install -y yarn
RUN sudo pip install pydoc-markdown 

# Set up the documentation environment
WORKDIR /home/autogen/autogen/website/
RUN yarn install --frozen-lockfile --ignore-engines

# Exposes the Yarn port for Docusaurus
EXPOSE 3000

# Pre-load popular Python packages
RUN pip install numpy pandas matplotlib seaborn scikit-learn requests urllib3 nltk pillow pytest beautifulsoup4

# Set the default command to bash

# Assuming your Docker build context is the root of the 'autogen' project
# and 'start.sh' is located in the 'autogen/website' directory
# Copy the start script from the autogen/website directory to the current working directory
# and change its ownership to 'autogen'
COPY --chown=autogen:autogen website/start.sh .
# Make the start script executable
RUN chmod +x start.sh
# Set the default command to execute the start script
#CMD ["./start.sh"]
CMD ["/bin/bash"]


