provider: AzureOpenAIChatCompletionClient
config:
  model: gpt-4.1
  azure_endpoint: https://trapi.research.microsoft.com/gcr/shared
  api_version: "2025-04-01-preview"
  azure_deployment: "gpt-4.1_2025-04-14"
  azure_ad_token_provider:
    provider: autogen_ext.auth.azure.AzureTokenProvider
    config:
      provider_kind: DefaultAzureCredential
      scopes:
        - api://trapi/.default
