"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import agent_worker_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class AgentRpcStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    OpenChannel: grpc.StreamStreamMultiCallable[
        agent_worker_pb2.Message,
        agent_worker_pb2.Message,
    ]

class AgentRpcAsyncStub:
    OpenChannel: grpc.aio.StreamStreamMultiCallable[
        agent_worker_pb2.Message,
        agent_worker_pb2.Message,
    ]

class AgentRpcServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def OpenChannel(
        self,
        request_iterator: _MaybeAsyncIterator[agent_worker_pb2.Message],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[agent_worker_pb2.Message], collections.abc.AsyncIterator[agent_worker_pb2.Message]]: ...

def add_AgentRpcServicer_to_server(servicer: AgentRpcServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
