import * as React from "react";
import Icon from "./icons";

const Disclosure = () => {
  const [open, setOpen] = React.useState(false);
  return (
    <div className="mt-4 text-primary py-3  mb-6  border-secondary ">
      <div>
        Images shown by this tool are generated by a machine learning model.
        Learn more about{" "}
        <span
          role={"button"}
          onClick={() => {
            setOpen(!open);
          }}
          className="inline-block border-b-2 border-accent"
        >
          {" "}
          how it works{" "}
        </span>
      </div>

      {open && (
        <div className="py-2 text-xs">
          A machine learning model is trained to generate images that capture
          the concepts described in the text prompt you provide.
        </div>
      )}
    </div>
  );
};
export default Disclosure;
